### ISSUE TITLE
unit tests fail on PHP 7.2 cause of array_key_first

### ISSUE THREAD

**Issue by JonasWijne** [regnerisch/sets#1]
In your composer.json you define the PHP version to be ^7.2
`array_key_first` is introduced in 7.3 https://www.php.net/manual/en/function.array-key-first.php

--- 

Unit test fails in `src/DetectTypeMap.php`
possible fix: 
`$item = reset($array);``

---

Keep up the good work

**Comment by regnerisch** [comment]
Resolved in v0.4.0

Thank you for reporting :)
