### ISSUE TITLE
Arrayy

### ISSUE THREAD

**Issue by voku** [regnerisch/sets#3]
Hi, I also created an array library that checks types of array elements, but I used phpdoc for that. Do you think we can merge this approaches? https://github.com/voku/Arrayy#phpdoc-property-checking

**Comment by regnerisch** [comment]
You mean merging your implementation into mine?

**Comment by voku** [comment]
Yep, merge or use it I don't know, I only saw two implementations for the same purpose and maybe we can combine / merge this approaches?  

PS: it also supports generators for all methods, so that the user of the library is able to write memory friendly code in an easy way :)

**Comment by regnerisch** [comment]
But wouldn't that mean I create "Arrayy2"? I think I did a good job with the actual implementation, but I will check your code for inspiration and me implement some things. Thank you :)
